
/* Define your language here:
 * Available languages:
 * - EN : English
 * - ES : Spanish (Español)
 */

//#define LANG_SET_EN
#define LANG_SET_ES

#ifdef LANG_SET_EN
#define LANG_WM_HTTP_SCRIPT_NTP_MSG_1           "Your timezone is : "
#define LANG_WM_HTTP_PORTAL_OPTIONS_1           "Configuration"
#define LANG_WM_HTTP_PORTAL_OPTIONS_2           "Information"
#define LANG_WM_HTTP_PORTAL_OPTIONS_3           "Exit Portal"
#define LANG_WM_HTTP_FORM_START_SSID            "SSID"
#define LANG_WM_HTTP_FORM_START_PASS            "Password"
#define LANG_WM_HTTP_FORM_END_SAVE              "Save"
#define LANG_WM_HTTP_SAVED_1                    "<b>Credentials Saved</b><br>Try connecting ESP to the {x}/{x1} network. Wait around 10 seconds then check <a href=\"/\">if it's OK.</a> "
#define LANG_WM_HTTP_SAVED_2                    "<p/>The {v} AP will run on the same WiFi channel of the {x}/{x1} AP. You may have to manually reconnect to the {v} AP."
#define LANG_WM_HTTP_AVAILABLE_PAGES_TITLE      "Available Pages"
#define LANG_WM_HTTP_AVAILABLE_PAGES_1          "Page"
#define LANG_WM_HTTP_AVAILABLE_PAGES_2          "Function"
#define LANG_WM_HTTP_AVAILABLE_PAGES_MENU       "Menu page."
#define LANG_WM_HTTP_AVAILABLE_PAGES_WIFI       "Show WiFi scan results and enter WiFi configuration."
#define LANG_WM_HTTP_AVAILABLE_PAGES_SAVE       "Save WiFi configuration information and configure device. Needs variables supplied."
#define LANG_WM_HTTP_AVAILABLE_PAGES_CLOSE      "Close the configuration server and configuration WiFi network."
#define LANG_WM_HTTP_AVAILABLE_PAGES_INFO       "This page."
#define LANG_WM_HTTP_AVAILABLE_PAGES_RESET      "Delete WiFi configuration and reboot. ESP device will not reconnect to a network until new WiFi configuration data is entered."
#define LANG_WM_HTTP_AVAILABLE_PAGES_STATE      "Current device state in JSON format. Interface for programmatic WiFi configuration."
#define LANG_REPORTSTATUS_1                     "Configured to connect to AP <b>"
#define LANG_REPORTSTATUS_2                     " and connected</b> on IP <a href=\"http://"
#define LANG_REPORTSTATUS_3                     " but not connected.</b>"
#define LANG_REPORTSTATUS_4                     "No network configured."
#define LANG_HANDLEROOT_OPTIONS                 "Options"
#define LANG_HANDLEROOT_ON                      "on"
#define LANG_CONFIG_TITLE                       "Config ESP"
#define LANG_CONFIG_CONFIG                      "<h2>Configuration</h2>"
#define LANG_CONFIG_NONETWORK                   "No networks found. Refresh to scan again."
#define LANG_CONFIG_REUSE                       "<small>To reuse already connected AP, leave SSID & password fields empty</small>"
#define LANG_WIFISAVE_CREDSAVED                 "Credentials Saved"
#define LANG_CLOSEPORTAL_1                      "Close Server"
#define LANG_CLOSEPORTAL_2                      "My network is <b>"
#define LANG_CLOSEPORTAL_3                      "IP address is <b>"
#define LANG_CLOSEPORTAL_4                      "Portal closed...<br><br>"
#define LANG_INFO_1                             "Info"
#define LANG_INFO_2                             "Trying to connect"
#define LANG_INFO_3                             "<h2>WiFi Information</h2>"
#define LANG_INFO_4                             "<h3>Device Data</h3>"
#define LANG_INFO_5                             "<thead><tr><th>Name</th><th>Value</th></tr></thead><tbody><tr><td>Chip ID</td><td>"
#define LANG_INFO_6                             "<tr><td>Flash Chip ID</td><td>"
#define LANG_INFO_7                             "<tr><td>IDE Flash Size</td><td>"
#define LANG_INFO_8                             "<tr><td>Real Flash Size</td><td>"
#define LANG_INFO_9                             " bytes</td></tr>"
#define LANG_INFO_10                            "<tr><td>Access Point IP</td><td>"
#define LANG_INFO_11                            "<tr><td>Access Point MAC</td><td>"
#define LANG_INFO_12                            "<tr><td>SSID</td><td>"
#define LANG_INFO_14                            "<tr><td>Station IP</td><td>"
#define LANG_INFO_15                            "<tr><td>Station MAC</td><td>"
#define LANG_INFO_16                            "<p/>More information about ESPAsync_WiFiManager at"
#define LANG_INFO_17                            "<p/><a href=\"https://github.com/khoih-prog/ESPAsync_WiFiManager\">https://github.com/khoih-prog/ESPAsync_WiFiManager</a>"
#define LANG_RESET_1                            "WiFi Information"
#define LANG_RESET_2                            "Resetting"
#endif

#ifdef LANG_SET_ES
#define LANG_WM_HTTP_SCRIPT_NTP_MSG_1           "Tu zona horaria es : "
#define LANG_WM_HTTP_PORTAL_OPTIONS_1           "Configuracion"
#define LANG_WM_HTTP_PORTAL_OPTIONS_2           "Informacion"
#define LANG_WM_HTTP_PORTAL_OPTIONS_3           "Salir del panel"
#define LANG_WM_HTTP_FORM_START_SSID            "Nombre"
#define LANG_WM_HTTP_FORM_START_PASS            "Contrasena"
#define LANG_WM_HTTP_FORM_END_SAVE              "Guardar"
#define LANG_WM_HTTP_SAVED_1                    "<b>Credenciales guardadas</b><br>Prueba conectandote a la red {x}/{x1}. Espera 10 segundos y revisa <a href=\"/\">si esta funcionando.</a> "
#define LANG_WM_HTTP_SAVED_2                    "<p/>El punto de acceso ({v}) correra en el mismo canal que la red {x}/{x1}. Podras tener que reconectarte manualmente a la red {v}."
#define LANG_WM_HTTP_AVAILABLE_PAGES_TITLE      "Paginas disponibles"
#define LANG_WM_HTTP_AVAILABLE_PAGES_1          "Pagina"
#define LANG_WM_HTTP_AVAILABLE_PAGES_2          "Funcion"
#define LANG_WM_HTTP_AVAILABLE_PAGES_MENU       "Menu principal."
#define LANG_WM_HTTP_AVAILABLE_PAGES_WIFI       "Muestra resultados del escaneo WiFi y entra a la configuración"
#define LANG_WM_HTTP_AVAILABLE_PAGES_SAVE       "Guarda la configuracion y la aplica. Necesita suministrarle variables."
#define LANG_WM_HTTP_AVAILABLE_PAGES_CLOSE      "Cerrar el portal de configuracion y la red de acceso."
#define LANG_WM_HTTP_AVAILABLE_PAGES_INFO       "Esta pagina."
#define LANG_WM_HTTP_AVAILABLE_PAGES_RESET      "Borra las redes guardadas y reinicia. Tendra que configurarlas de nuevo."
#define LANG_WM_HTTP_AVAILABLE_PAGES_STATE      "Estado actual de la conexion en JSON."
#define LANG_REPORTSTATUS_1                     "Configurado para conectarse a la red <b>"
#define LANG_REPORTSTATUS_2                     " y actualmente conectado</b> con la IP <a href=\"http://"
#define LANG_REPORTSTATUS_3                     " pero no esta conectado actualmente.</b>"
#define LANG_REPORTSTATUS_4                     "No hay ninguna red configurada"
#define LANG_HANDLEROOT_OPTIONS                 "Opciones"
#define LANG_HANDLEROOT_ON                      "en"
#define LANG_CONFIG_TITLE                       "Configurar"
#define LANG_CONFIG_CONFIG                      "<h2>Configuracion</h2>"
#define LANG_CONFIG_NONETWORK                   "No se encontraron redes. Refresca la pagina para escanear de nuevo."
#define LANG_CONFIG_REUSE                       "<small>Para reusar una red ya configurada, dejar el el nombre y contrasena vacios</small>"
#define LANG_WIFISAVE_CREDSAVED                 "Credenciales guardadas"
#define LANG_CLOSEPORTAL_1                      "Cerrar portal"
#define LANG_CLOSEPORTAL_2                      "Conectado a la red <b>"
#define LANG_CLOSEPORTAL_3                      "Con la IP <b>"
#define LANG_CLOSEPORTAL_4                      "Portal cerrado...<br><br>"
#define LANG_INFO_1                             "Info"
#define LANG_INFO_2                             "Intentando conectarse"
#define LANG_INFO_3                             "<h2>Informacion de WiFi</h2>"
#define LANG_INFO_4                             "<h3>Datos del dispositivo</h3>"
#define LANG_INFO_5                             "<thead><tr><th>Nombre</th><th>Valor</th></tr></thead><tbody><tr><td>S.N. Chip</td><td>"
#define LANG_INFO_6                             "<tr><td>S.N. Memoria</td><td>"
#define LANG_INFO_7                             "<tr><td>Tamano de flash en IDE</td><td>"
#define LANG_INFO_8                             "<tr><td>Tamano de flash real</td><td>"
#define LANG_INFO_9                             " bytes</td></tr>"
#define LANG_INFO_10                            "<tr><td>IP del punto de acceso</td><td>"
#define LANG_INFO_11                            "<tr><td>MAC del punto de acceso</td><td>"
#define LANG_INFO_12                            "<tr><td>Nombre (SSID)</td><td>"
#define LANG_INFO_14                            "<tr><td>IP del dispositivo</td><td>"
#define LANG_INFO_15                            "<tr><td>MAC del dispositivo</td><td>"
#define LANG_INFO_16                            "<p/>Para mas info acerca de ESPAsync_WiFiManager ver"
#define LANG_INFO_17                            "<p/><a href=\"https://github.com/khoih-prog/ESPAsync_WiFiManager\">https://github.com/khoih-prog/ESPAsync_WiFiManager</a>"
#define LANG_RESET_1                            "Informacion de WiFi"
#define LANG_RESET_2                            "Reiniciando"
#endif